---
title: "Statistical Inference Course Project"
author: "Venkat Ram Rao"
date: "10/23/2020"
output:
  word_document: default
  pdf_document: default
---

## Title: Statistical Inference Course Project
## Author: Venkat Ram Rao


## Overview
<!-- 
This document consists of 2 parts. Each part consists of an analysis for the Statistical Inference Course Project 
 Part 1: Investigate the exponential distribution in R (rexp(n, lambda) with lambda = 0.2) and compare it with the Central Limit Theorem. 
Part 2: Load and analyze the ToothGrowth data in the R datasets package 
-->


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## -------------------PART 1--------------------
## Part 1 Overview:


## Simulation 1: Mean or 1000 samples of size 40, Lambda 0.2

```{r}
mns = NULL
vars = NULL
for (i in 1 : 1000) 
  {
  mns = c(mns, mean(rexp(40,.2)))
  vars = c(vars, sd(rexp(40,.2))^2)
}

mean(mns)
sd(mns)

mean(vars)
sd(vars)

h<-hist(mns, breaks=10, col="red", xlab="Mean",
   main="Histogram with Normal Curve")
xfit<-seq(min(mns),max(mns),length=40)
yfit<-dnorm(xfit,mean=mean(mns),sd=sd(mns))
yfit <- yfit*diff(h$mids[1:2])*length(mns)
lines(xfit, yfit, col="blue", lwd=2)
```

## Simulation 2: Standard Deviation or 1000 samples of size 40, Lambda 0.2

```{r}

h<-hist(vars, breaks=10, col="red", xlab="Variance",
   main="Histogram with Normal Curve")
xfit<-seq(min(vars),max(vars),length=40)
yfit<-dnorm(xfit,mean=mean(vars),sd=sd(vars))
yfit <- yfit*diff(h$mids[1:2])*length(vars)
lines(xfit, yfit, col="blue", lwd=2)
```

## Simulation 3 - Plot of the Cumulative Means As tests Progress
```{r}
library(ggplot2)
avg=NULL
n <- 1000
avg <- cumsum(mns)/(1:n)
 df <- data.frame(x=1:n,y=avg[1:n])

ggplot(data=df, aes(x=x, y=y)) +
  geom_line(color="red")+
  geom_point()

```



```{r}
data("ToothGrowth")
dim(ToothGrowth)
str(ToothGrowth)

library(ggplot2)
OJ = ToothGrowth$len[ToothGrowth$supp == 'OJ']
VC = ToothGrowth$len[ToothGrowth$supp == 'VC']
mean(OJ)
sd(OJ)
mean(VC)
sd(VC)

half = ToothGrowth$len[ToothGrowth$dose == 0.5]
one = ToothGrowth$len[ToothGrowth$dose == 1]
two = ToothGrowth$len[ToothGrowth$dose == 2]
mean(two)
sd(two)
mean(one)
sd(one)
mean(half)
sd(half)

t.test(OJ, VC, alternative = "greater", paired = FALSE, conf.level = 0.95)

t.test(two, one, alternative = "greater", paired = FALSE, conf.level = 0.95)

t.test(one, half, alternative = "greater", paired = FALSE, conf.level = 0.95)

```
